#!/usr/bin/env bash
# A script that starts nginx without process id while it listens on port 80
cp -f /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
rm /run/nginx.pid
