#!/usr/bin/env bash
# A Bash script that displays the content of the file /etc/passwd
# username, id, directory

path="/etc/passwd"

while file_info= read -r line
do
	echo "$line" | cut -d":" -f1,3,6
done < "$path"
