#!/usr/bin/env bash
# A Bash script that displays the content of the file /etc/passwd
# displays only the username, id and directory
# IFS: Internal Field Separator

file="/etc/passwd"
while IFS= read -r line
do
    echo "$line" | cut -d':' --fields=1,3,6
done < "$file"
